---
# We are actually a mix of languages, but need to start from somewhere
language: php
php:
  - '7.0'

addons:
  apt:
    packages:
      - libxml2-utils
      - parallel

install:
  - DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install unifont imagemagick fontforge maven python3
  - git clone https://github.com/mike42/fontscale-util
  - (cd fontscale-util && mvn clean package)
  - (cd utils && composer install)
  - cp fontscale-util/target/fontscale-util-*-jar-with-dependencies.jar utils/fontscale-wrapper/fontscale-utils.jar
  - which php
  - which python
  - which python3
  - printf "\n" | pecl install imagick

script:
  - ./configure
  - make -j64
